### ISSUE TITLE
Add more Lisp implementations to CI

### ISSUE THREAD

**Issue by ruricolist** [ruricolist/serapeum#102]
Currently we only test against SBCL and CCL because they were the only ones I could get working in CI. There may be other options now. I would at least like to test against ABCL and ECL as well, ideally also Allegro.

**Comment by phoe** [comment]
It should be possible to use Roswell for installing SBCL/CCL/ABCL/ECL/CLISP/Allegro and to run the CI on GitHub Actions. See https://roswell.github.io/GitHub-Actions.html

**Comment by phoe** [comment]
FYI: there is also a utility from @svetlyak40wt that might be useful in the future - see https://40ants.com/ci/#x-2840ANTS-CI-3A-3A-40RUN-TESTS-2040ANTS-DOC-2FLOCATIVES-3ASECTION-29

**Comment by svetlyak40wt** [comment]
Feel free to ask me any questions related to my tool.

**Comment by svetlyak40wt** [comment]
There is another useful one, for showing build status for multiple implementations/OSe: https://github-actions.40ants.com/
