### ISSUE TITLE
Maybe include WITH-BRANCHING

### ISSUE THREAD

**Issue by phoe** [ruricolist/serapeum#103]
https://github.com/phoe/with-branching

Someone pointed out to me that this utility basically extends `serapeum:with-boolean` with operators that can avoid "deleting unusable code" warnings. This, and a bit of syntax sugar for having multiple booleans.

Would you consider merging my code into Serapeum? I see a possible way forward like this:

* modifying the expansion of `with-boolean` to support `branch-{if,when,unless}`,
* adding `branch-{if,when,unless}` (and possibly considering some other names for these),
* adding `with-booleans` as syntax sugar for multiple boolean variables.

**Comment by ruricolist** [comment]
I will look into it as soon as I have a chance. I would definitely like to get rid of those unusable code warnings if possible.

**Comment by phoe** [comment]
OK - my code isn't rocket science, as a recent Hacker News comment mentioned. You should be able to figure everything out by macrostepping the test cases.

**Comment by ruricolist** [comment]
I would definitely like to merge this into Serapeum.

**Comment by phoe** [comment]
OK - do you have the time to modify my code and tests yourself (it should be clean enough), or would you prefer if I prepared a PR later?

**Comment by ruricolist** [comment]
A PR makes more sense to me, if you have time. Your plan looks good.

**Comment by phoe** [comment]
OK, should be able to do this tomorrow or so.

**Comment by phoe** [comment]
#105 - see the questions in the PR.

**Comment by phoe** [comment]
Closed via #105.
