### ISSUE TITLE
Compilation errors on Serapeum from master

### ISSUE THREAD

**Issue by phoe** [ruricolist/serapeum#104]
SBCL 2.1.11 on Linux amd64.

```lisp
CL-USER> (asdf:test-system :serapeum)
; (...)

 Did 1383 checks.
    Pass: 1383 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)

; 
; compilation unit finished
;   caught 2 fatal ERROR conditions
;   caught 3 ERROR conditions
;   caught 5 WARNING conditions
;   caught 3 STYLE-WARNING conditions
```

Should I be worried about the fatal errors and errors mentioned in the compilation unit?

**Comment by ruricolist** [comment]
No. There are tests that call compile at runtime to make sure compile time errors and warnings are signaled.

**Comment by phoe** [comment]
I assume you could handle these errors in order to prevent them from propagating further and *also* check that they are signaled from inside the compiler. Or is that impossible for some reason?

**Comment by phoe** [comment]
Yep, I see - these are SBCL compiler noisiness. I don't know how to calm it down, but it doesn't matter much for the test result.
