### ISSUE TITLE
nhook: Revamped typed hooks

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#106]
@BlueFlo0d did some amazing work in https://github.com/atlas-engineer/nhooks and revamped the serapeum/contrib/hooks with the following highlights:

- Compile-time and run-time function type-checking (on SBCL at least)!  No more need for the ugly function-and-class-writing macro.
- The `handler`s are now optional and regular functions can be directly added to hooks.
- The hook has only one list of handlers.  It's an alist and the second element is a boolean, `T` for enabled handlers and `NIL` for disabled ones.

**Comment by Ambrevar** [comment]
In my opinion, it largely supersedes serapeum/contrib/hooks but it's not backward compatible.

The only drawback that I see currently is that CCL type checking is completely gone.  Any idea how to implement it?  See https://github.com/atlas-engineer/nhooks/issues/6.

**Comment by ruricolist** [comment]
To be clear, are you saying that I should remove/deprecate serapeum/contrib/hooks in favor of nhooks, or that nhooks should replace serapeum/contrib/hooks?

**Comment by Ambrevar** [comment]
I don't know, actually.

Removing contrib/hooks means losing backward compatibility, which is
rather a big move for a library like Serapeum.

Better options include recommending nhooks in Serapeum's readme, and
(optionally) including nhooks in the contrib/.

I don't know if there is any advantage in including nhooks into serapeum
vs. maintaining it separately.

**Comment by ruricolist** [comment]
I've just added a deprecation notice and a link to the new project for the moment.

**Comment by Ambrevar** [comment]
Thanks!
