### ISSUE TITLE
Potentially improper use of LOAD-TIME-VALUE in STATIC-LET?

### ISSUE THREAD

**Issue by Hexstream** [ruricolist/serapeum#113]
Has the LOAD-TIME-VALUE trick been thoroughly tested on multiple implementations? Because I had done this for the first release of [first-time-value](https://www.hexstreamsoft.com/libraries/first-time-value/) but I later had to [fix it](https://github.com/Hexstream/first-time-value/commit/90d3b0d5cb1c69c3b8ae17af18184a83c026c533) because it didn't work properly in some situations on CCL. (The issue is easy to work around by using the value cell of a gensym, see [the first-time-value source code](https://github.com/Hexstream/first-time-value/blob/master/main.lisp) for a simple example.)

What I had tentatively concluded at the time is that the value returned by LOAD-TIME-VALUE should always be treated as a real literal that you can't safely modify, even if the value is not explicitly declared read-only. I'm not sure if I was correct, but you may like to investigate and test further.

**Comment by Hexstream** [comment]
[Confirmed](https://mov.im/?blog/phoe%40movim.eu/load-time-value-or-how-i-started-worrying-about-static-let-again-RzrzQT), it seems. ;P

(I don't think the presented "solution" is sane or optimal, but that's another story...)

**Comment by ruricolist** [comment]
I believe this has been addressed so I'm closing this issue. Feel free to reopen if there's something I've overlooked.
