### ISSUE TITLE
Borrow the extensible sequence implementation from SPLIT-SEQUENCE for testing

### ISSUE THREAD

**Issue by phoe** [ruricolist/serapeum#122]
While looking at the last comments at #121 I realized that we could borrow [the extended sequence implementation from split-sequence](https://github.com/sharplispers/split-sequence/blob/89a10b4d697f03eb32ade3c373c4fd69800a841a/tests.lisp#L9-L25) and actually test Serapeum's sequence functions using it on SBCL and ABCL.

**Comment by ruricolist** [comment]
Great idea. Given that it's using the `sb-sequence` package, though, does it actually work on ABCL?

**Comment by phoe** [comment]
I have completely no idea, and I do not think `split-sequence` is tested on ABCL. We might want to use https://github.com/Shinmera/trivial-extensible-sequences instead.
