### ISSUE TITLE
Proposal: local function aliases

### ISSUE THREAD

**Issue by mmontone** [ruricolist/serapeum#124]
Hello,

I'm thinking that perhaps having local function aliases would be a good utility to have.

It may be just me perhaps, but I often like to bind large function names to shorter, locally, like this:

```lisp
(flet-aliases ((-> json:encode-object-member))
    (with-output-to-string (json:*json-output*)
      (json:with-object ()
	(-> :id (vs::video-id video))
	(-> :title (vs::title video))
	(-> :status (vs::status video)))))
```

or this:

```lisp
(flet-aliases ((-> access:accesses))
    (list :id (-> video :id) 
           :title (-> video :title)
           :description (-> video :description)))
```

This is my `flet-aliases` definition:

```lisp
(defmacro flet-aliases (bindings &body body)
  "Bind function aliases."
  `(flet ,(loop for binding in bindings
	       collect `(,(first binding) (&rest args)
			  (apply #',(second binding) args)))
     ,@body))
```

Do you think this is useful? Is there some other idiom for this? I have no idea if others are used to program like this.

Feel free to discard this :)

**Comment by ruricolist** [comment]
This can be done with fbind.

**Comment by mmontone** [comment]
Oh great. Thanks.
