### ISSUE TITLE
defmemo

### ISSUE THREAD

**Issue by mattbeshara** [ruricolist/serapeum#144]
Hi there!
I'd like to use memoization in some code I'm writing, and not wanting to import more libraries than is necessary, I did a grep for `defmemo` in my Quicklisp directory to see what I already had around which might provide it.  It turned up the sample implementation of `defmemo` in Serapeum's `README.md`.  It seems odd to me that, despite that implementation being present in the readme, it's not actually available as part of Serapeum itself.  Should it be?  Or would it be better for me to either copy/paste that sample implementation into my own code, or use another library which provides `defmemo`?
Thanks for you time!

**Comment by ruricolist** [comment]
I would usually recommend fare-memoization.

**Comment by mattbeshara** [comment]
Great, thank you!
