### ISSUE TITLE
LENGTH<= and LENGTH>= are incorrectly implemented for the non-binary case

### ISSUE THREAD

**Issue by miklos1** [ruricolist/serapeum#147]
A failing example:
```
CL-USER> (length>= '() '(1) '(2))
T
```
The above should clearly return NIL, since `'()` is strictly shorter than `'(1)`.  Looking at the code, the reason is obvious:
```lisp
(defun length>= (&rest seqs)
  "Is each length-designator in SEQS longer or as long as the next?
A length designator may be a sequence or an integer."
  (not (apply #'length< seqs)))
```
`>=` is the logical inversion of `<` only in the two-argument case, but not as an n-ary operator.

**Comment by ruricolist** [comment]
Thanks for reporting this.
