### ISSUE TITLE
Add stable-set-difference

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#148]
`set-difference` is a notorious pitfall in Common Lisp since it does not guarantee the order of the returned elements, which is arguably counter-intuitive.

Thus I propose Serapeum includes a `stable-set-difference` function.

**Comment by ruricolist** [comment]
Good idea! Good name for it too. This is true of all the other set functions also. A stable-union is something I would reach for often.

**Comment by Ambrevar** [comment]
@ruricolist Thanks a lot for the prompt implementation
@aartaka It's now in! :)

**Comment by aartaka** [comment]
Hooray!
