### ISSUE TITLE
Compile error (possibly with stable-set-difference)

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#149]
I get the following compilation error in GitHub's CI when using CCL on the latest Serapeum (https://github.com/atlas-engineer/nyxt/actions/runs/4807278934/jobs/8555838069?pr=2934):

```log
 ;Compiler warnings for "home:work;nyxt;nyxt;_build;serapeum;lists.lisp.newest" :
caught error #<SIMPLE-ERROR #x3020079D05ED>
Serious errors encountered during compilation of "/home/runner/work/nyxt/nyxt/_build/serapeum/lists.lisp"
;   In MEM: Illegal reference to lexically defined variable #:UTEST-NOT344863.
;   In MEM: Illegal reference to lexically defined variable #:UTEST344862.
;   In MEM: Illegal reference to lexically defined variable #:UKEY344861.
;   In STABLE-SET-DIFFERENCE: Invalid program: Illegal reference to lexically defined variable #:UKEY344861.
;   In STABLE-SET-DIFFERENCE: Unused lexical variable #:UTEST-NOT344863
;   In STABLE-SET-DIFFERENCE: Unused lexical variable #:UTEST344862
;   In STABLE-SET-DIFFERENCE: Unused lexical variable #:UKEY344861
Error: Process completed with exit code 17.
```

Interestingly I cannot reproduce locally.  Any idea?

**Comment by aadcg** [comment]
@Ambrevar I'm able to reproduce locally. Notice that Guix's version of serapeum is a bit old. You need to ensure that you're running the tests locally with the right version. For example, by cloning serapeum at `~/common-lisp/serapeum/`.

```log
 Did 1812 checks.
    Pass: 1810 (99%)
    Skip: 0 ( 0%)
    Fail: 2 ( 0%)

 Failure Details:
 --------------------------------
 STABLE-SET-DIFFERENCE in LISTS []: 
      Unexpected Error: #<CCL::SIMPLE-PROGRAM-ERROR #x302002DB1ADD>
Invalid program: In the form ((LIST1 (LAMBDA NIL (COERCE (RANGE 100) 'LIST))) (LIST2 (LAMBDA NIL (SHUFFLE (FILTER-MAP (LAMBDA (X) (WHICHEVER X NIL)) LIST1))))), (LIST1 (LAMBDA NIL (COERCE (RANGE 100) 'LIST))) is not a symbol or lambda expression..
 --------------------------------
 --------------------------------
 LENGTH-FNS in SEQUENCES []: 
      Unexpected Error: #<CCL::SIMPLE-PROGRAM-ERROR #x302002D6A69D>
Invalid program: In the form ((LEN (LAMBDA NIL (RANDOM-IN-RANGE 2 10))) (SEQ-LENS (LAMBDA NIL (LOOP REPEAT LEN COLLECT (RANDOM 10)))) (SEQ-TYPES (LAMBDA NIL (LOOP REPEAT LEN COLLECT (RANDOM-ELT '(LIST VECTOR INTEGER)))))), (LEN (LAMBDA NIL (RANDOM-IN-RANGE 2 10))) is not a symbol or lambda expression..
 --------------------------------
```

**Comment by aadcg** [comment]
Sorry, my above comment was with respect to testing `serapeum` on CCL.

With respect to loading `serapeum` on CCL, the subject of this issues, I can't reproduce it locally as well.

**Comment by Ambrevar** [comment]
The problem is most likely due to the use of an old dependency.  Nyxt's pipeline pins all deps, so this may be why.
Any idea which dep could infer with the loading of `lists.lisp`?

**Comment by ruricolist** [comment]
I've tested with CCL 1.12.1 but was not able to reproduce.

**Comment by ruricolist** [comment]
Actually, I think I know what the problem is. I've pushed a commit that should fix it.

**Comment by Ambrevar** [comment]
Wow, it worked!  Thanks!

**Comment by ruricolist** [comment]
The ECL problem looks like old fiveam again. As for GitHub CI, which one do you mean?

**Comment by Ambrevar** [comment]
Guix has Fiveam 1.4.2, which is the latest stable.  If it's really the problem, could it be possible to support the latest stable Fiveam?  Otherwise we would need to package a special Fiveam just for Serapeum.

I'm talking about serapeum's CI: https://github.com/ruricolist/serapeum/actions/runs/4814783572

**Comment by aadcg** [comment]
> Reopening, because it fails on ECL

It might be worth noting that the CI for ECL was disabled in commit db4185593f66641c6f5f9851a84417a5f81c30b2.

What's the motivation behind this commit @ruricolist? Thanks.

**Comment by ruricolist** [comment]
I believe ECL was consistently failing to install.

**Comment by ruricolist** [comment]
I've opened an issue on the fiveam repo suggesting a new stable release: https://github.com/lispci/fiveam/issues/100. In the meantime I've removed the `for-all*` macro from the test suite.

**Comment by ruricolist** [comment]
Note that ccl-bin also regularly fails to install with Roswell in CI.

**Comment by Ambrevar** [comment]
Yes, I know this issue, to work around it you can specify the CCL version, for instance replace `ccl-bin` with `ccl-bin/1.12.1`.

Alternatively, use Guix instead of Roswell, it's much more reliable but won't work on macOS.  Although in my experience Roswell does not support installing ECL nor CCL on macOS, so the difference would only matter for SBCL on macOS.

**Comment by ruricolist** [comment]
Thanks! Pinning the versions seems to have fixed the Roswell installs for CCL and ECL.

**Comment by Ambrevar** [comment]
Any idea about the ECL issue then?

**Comment by ruricolist** [comment]
Sorry, what ECL issue do you mean?

**Comment by Ambrevar** [comment]
Issue https://github.com/ruricolist/serapeum/issues/149#issuecomment-1525935128, but never mind, I tried again on Serapeum's master and it's working now.  A fix must have landed since then.
