### ISSUE TITLE
ABCL issue in strings / whitespace in Windows

### ISSUE THREAD

**Issue by PiotrWasik** [ruricolist/serapeum#154]
currently:

Error loading C:/Users/piotr/AppData/Local/cache/common-lisp/abcl-1.9.2-fasl43-win-x64/C/Users/piotr/quicklisp/dists/ultralisp/software/ruricolist-serapeum-20230613203226/strings.abcl at line 24 (offset 2125)
#<THREAD "interpreter" native {2BF31A7A}>: Debugger invoked on condition of type SIMPLE-ERROR
  SERAPEUM::+STORAGE-FOR-DEFLEX-VAR-WHITESPACE+ is an already defined constant whose value "
♀♂á" is not equal to the provided initial value "
♀♂á" under SERAPEUM::SAME-LITERAL-P.
Restarts:
  0: IGNORE                        Retain the current value.
  1: CONTINUE                      Try to redefine the constant.

It is possible to continue, but indeed something is wrong as both values are different.

No issue is reported when I remove #. from (defconst whitespace ...)
Perhaps it is more portable not to have #. there?

**Comment by ruricolist** [comment]
Removing the #. sounds like a good idea. Do you want to make a pull request?

**Comment by PiotrWasik** [comment]
thanks :)
