### ISSUE TITLE
count-cpus fails with :MEMOIZE NIL

### ISSUE THREAD

**Issue by Gleefre** [ruricolist/serapeum#156]
```lisp
* (serapeum:count-cpus :memoize nil)

debugger invoked on a UNDEFINED-FUNCTION @52A00904 in thread
#<THREAD tid=34684 "main thread" RUNNING {1004958113}>:
  SERAPEUM:NIX is a macro, not a function.
```

This seems to be caused by `threads.lisp` being loaded before the `control-flow.lisp` file, resulting in `serapeum:nix` being defined after the `serapeum:count-cpus` where it was supposed to be a function.

**Comment by ruricolist** [comment]
Thansk for reporting this. I've pushed up a fix. If you have time, I'd appreciate knowing if you're still seeing the bug.

**Comment by Gleefre** [comment]
I don't see the bug anymore
