### ISSUE TITLE
Util suggestion: drop-until, take-until

### ISSUE THREAD

**Issue by bo-tato** [ruricolist/serapeum#158]
I use them reasonably often, and I'm not the only one, I saw they're added [here](https://github.com/GrammaTech/cl-utils/blob/master/misc.lisp). maybe it makes sense to add to serapeum? Most simple implementation would be as there:
```
(defun drop-until (pred seq)
  (drop-while (complement pred) seq))
```
Personally I like to have it take a predicate or a value:
```
(defun drop-until (pred-or-val seq)
  (let ((pred (if (functionp pred-or-val)
                  pred-or-val
                  (lambda (x) (equal x pred-or-val)))))
    (drop-while (complement pred) seq)))
```
so then ie instead of writing `(drop-until (lambda (n) (equal n 7)) (range 10))` I can just write `(drop-until 7 (range 10))`

**Comment by ruricolist** [comment]
I've added these. For the case of drop-until with a constant, I think the best thing would be to use `eqls`, which returns a function to test for equality: `(drop-until (eqls 7) (range 10))`.
