### ISSUE TITLE
Fails to load in clozure ccl

### ISSUE THREAD

**Issue by bon** [ruricolist/serapeum#167]
Using clozure 1.12.2 LinuxX8664 on Linux 6.7.0-arch3-1, loading serapeum version 20231021 from quicklisp with either `(ql:quickload :serapeum)` or `(asdf:load-system :serapeum)` runs CPU at 100% but never completes loading.

**Comment by ruricolist** [comment]
I haven't been able to reproduce this. It would be helpful if you could get a backtrace of what's happening when loading hangs, or paste the ASDF output.

**Comment by bon** [comment]
I tried to load it without my init file and it worked. Now it continues to work _with_ my init file so I can't reproduce the original issue. 
Closing. If it recurs I'll reopen.
