### ISSUE TITLE
Consider adding if-not, if-not-let

### ISSUE THREAD

**Issue by kilianmh** [ruricolist/serapeum#172]
While using `if-let` I want the then clause to execute when one or all variables evaluate to `nil`. Currently with if-let that is not possible. To achieve that we can copy the code from `if-let` in alexandra and simply change [this line](https://gitlab.common-lisp.net/alexandria/alexandria/-/blob/master/alexandria-1/binding.lisp?ref_type=heads#L29) from
```common-lisp
(if (and ,@variables)
```
to 
```common-lisp
(if (not (and ,@variables))
```
Do you like the idea of adding this macro? If yes, then the name could also be `not-if-let`, `if-not-let`, or `let-if-not`.

**Comment by ruricolist** [comment]
If we add this, I think if should probably be as `if-not-let`, and we should probably also add `if-not`.

Do you have any examples of a situation where this macro could be useful? Nothing comes to mind for me.

**Comment by kilianmh** [comment]
>Do you have any examples of a situation where this macro could be useful?

Use case:
- large `then-form`
- short `else-form`

Here dummy code to showcase the difference `if-let` vs `if-not-let`:
```common-lisp
(if-let
  (variable-1 initial-form-1)
  (
  .
  .
  .
  .
  .
  )
  (error-resulting-from-variable-1-nil))
```
And here written with `if-not-let`
```common-lisp
(if-not-let
  (variable-1 initial-form-1)
  (error-resulting-from-variable-1-nil)
  (
  .
  .
  .
  .
  .
  ))
```

With `if-not-let`, the error is next to the code that caused it.
Especially with multiple nested `if-let` forms of this structure
the code is more readable when replaced by `if-not-let`.

>we should probably also add `if-not`

I guess, yes.

**Comment by ruricolist** [comment]
Interesting. I actually hadn't realized `if-let` bindings were in effect in the else clause. In that case I think the idea makes sense if you want to go ahead with a PR for `if-not` and `if-not-let`.
