### ISSUE TITLE
Package lock errors encountered when quickloading dependent library, spinneret

### ISSUE THREAD

**Issue by GrumpyOldGandalf** [ruricolist/serapeum#173]
See: https://github.com/ruricolist/spinneret/issues/99

I don't know if the problem is with spinneret's use of serapeum, or the way seraphim's package itself is defined (I note that package locking is explicit in the package.lisp listing), but I decided to let both projects know about the issue, since it is preventing use of another package (namely, reblocks) for me.

**Comment by ruricolist** [comment]
This has been fixed in Spinneret.
