### ISSUE TITLE
serapeum doesn't show up in the "utilities" category on quickdocs

### ISSUE THREAD

**Issue by phoe** [ruricolist/serapeum#25]
```
20:17 < cgay> phoe: serapeum doesn't show up in the "utilities" category on quickdocs: 
              http://quickdocs.org/search?q=utilities  you can find it by search for serapeum, but you have to know 
              the name first. not sure if you're the author...might be worth fixing.
```

**Comment by ruricolist** [comment]
I'll look into it, thanks.

**Comment by ruricolist** [comment]
This is because Serapeum doesn't have a Cliki page; Quickdocs extracts category info from Cliki.

**Comment by ruricolist** [comment]
I've created a Cliki page; we'll see if Serapeum shows up the right category when Quickdocs next updates.

**Comment by anticrisis** [comment]
Biennial update: Although a [Cliki](https://www.cliki.net/Serapeum) page exists, Serapeum still does not appear in the [Quickdocs Utilities](http://quickdocs.org/search?q=utilities) list. Maybe the issue is at [Quickdocs](https://github.com/quickdocs/quickdocs-updater).

**Comment by ruricolist** [comment]
I'm leaning towards the idea that it's down to a Quickdocs bug, since the Serapeum [API reference](http://quickdocs.org/serapeum/api) is produces is blank.

**Comment by ruricolist** [comment]
As of 2022 it is included: https://quickdocs.org/-/search?q=utilities.
