### ISSUE TITLE
serapeum/vector= Can't compile current version

### ISSUE THREAD

**Issue by defunkydrummer** [ruricolist/serapeum#28]
I cloned the current commit into my system. 

It can't compile because of an error on a format directive:

```
[package serapeum/vector=]..

; file: c:/portacle/projects/serapeum/vector=.lisp
; in: DEFCONSTRUCTOR BOUNDS
;     (SERAPEUM:DEFCONSTRUCTOR SERAPEUM/VECTOR=::BOUNDS
;       (SERAPEUM/VECTOR=::START1 ALEXANDRIA.0.DEV:ARRAY-INDEX)
;       (SERAPEUM/VECTOR=::END1 ALEXANDRIA.0.DEV:ARRAY-LENGTH)
;       (SERAPEUM/VECTOR=::START2 ALEXANDRIA.0.DEV:ARRAY-INDEX)
;       (SERAPEUM/VECTOR=::END2 ALEXANDRIA.0.DEV:ARRAY-LENGTH))
; 
; caught ERROR:
;   (during macroexpansion of (DEFCONSTRUCTOR BOUNDS
;     ...))
;   error in FORMAT: unknown format directive (character: Return)
;     Copy an instance of ~:@(~a~), optionally ~

;   overriding some or all of its slots.
;                                               ^
;   while processing indirect format string:
;     ~?
;      ^
.....; 
     ; compilation unit aborted
     ;   caught 2 fatal ERROR conditions
     ;   caught 1 ERROR condition
```

Thus, i can't compile the current version for spinneret, another fine, quality product from Ruricolist.

**Comment by ruricolist** [comment]
This is an interesting bug...

The only way I can think of that this could happen would be checking out Serapeum with Git on Windows with `core.autocrlf` set to `true`. In that case, the tilde-newline directive would be encoded locally as tilde-return-newline instead, which SBCL doesn't support.

Would you try checking it out with `autoclrf` set to `input`? If that fixes it, I'll commit a `.gitattributes` file to force the correct encoding.
