### ISSUE TITLE
scan seems to be wrong

### ISSUE THREAD

**Issue by sirherrbatka** [ruricolist/serapeum#29]
first, of, the order argument in the callback is REVERSE from the standard reduce. Secondly key callback is not applied to the next value, just to the previous, what's up with that?

**Comment by sirherrbatka** [comment]
Also, supplying initial-value will force skipping first-value in the sequence apparently.

**Comment by ruricolist** [comment]
I'm not sure if the implementation was bugged, but it was certainly overcomplicated, so I replaced it with something simpler and added tests to document the intended behavior. Does it behave as you expect now?

**Comment by sirherrbatka** [comment]
Implementation is certainly better, but i would argue that it does not follow the docstring description

"Instead of returning just the final result, `scan' returns a list
of the successive results at each step."
 (scan #'+ '(1 2 3 4))   => '(1 3 6 10)
Where did 1 came from? It is not the result of +. If it would be scan #'+ '(1 2 3 4) :initial-value 0 i would argee, but it is not how it works.

**Comment by ruricolist** [comment]
Reduce doesn't always call its function with two arguments:

```
(reduce #'+ '()) => 0
(reduce #'+ '(1)) => 1
```

The way scan is defined has the advantage that it gives meaningful results for a single-argument list and an empty list. If `(scan #'+ '(1))` returns nil, then what should `(scan #'+ '())` return? An error?

More importantly, though, scan (like reduce!) comes from APL, going back as far as Iverson's [Notation as a Tool of Thought](http://www.jsoftware.com/papers/tot.htm). A function that omitted the first element would have to be called something else.

I'm willing to change the docstring if it's confusing, however.

**Comment by sirherrbatka** [comment]
Yes, i think that either docstring or implementation should be changed.
