### ISSUE TITLE
Assort seems not working on vector

### ISSUE THREAD

**Issue by physcrf** [ruricolist/serapeum#31]
Hi,

When I try `assort` on vector like this:
```cl
(assort #(1 2 3))
```
it would signal an error
``` 
The value
  #(1)
is not of type
  SIMPLE-VECTOR
```
in SBCL 1.4.16.

I don't know if it is a bug or I write it wrong.

Best Regards

**Comment by ruricolist** [comment]
It was a bug, fixed now. Thanks for reporting it.
