### ISSUE TITLE
Basic summary statistics

### ISSUE THREAD

**Issue by ruricolist** [ruricolist/serapeum#33]
The statistical functions in Alexandria --  in particular `mean`, `variance`, and `standard-deviation` -- are attractive nuisances: authoritatively named functions in the most popular utility library, but written with no concern for numerical stability.

We are committed to not conflicting with Alexandria, but it would be a public service to export numerically stable alternatives to these functions.

**Comment by ruricolist** [comment]
Rather than functions consider macros -- e.g. `averaging`, along the lines of `summing` or `collecting`.

**Comment by jmercouris** [comment]
Why not submit fixes to Alexandria?

**Comment by ruricolist** [comment]
I once tried submitting a patch to alexandria-devel but might as well have dropped it down a well.

Is there some reason to think Alexandria has become more open? If so I would be willing to try submitting a fix.

**Comment by jmercouris** [comment]
No, I don't think anything has changed, just didn't have personal experience with it. Sorry to hear that.

**Comment by phoe** [comment]
> Is there some reason to think Alexandria development has become more open? If so I would be willing to try submitting a fix.

Yes - https://gitlab.common-lisp.net/alexandria/alexandria/ is actively accepting patches.

**Comment by ruricolist** [comment]
Thanks. I did recently open an account there to make an MR on a different project. I'll look into this.

**Comment by phoe** [comment]
OK. Should this issue stay open in meantime, or should it be moved to the Alexandria tracker (probably with some examples of faulting behavior)?

**Comment by ruricolist** [comment]
Looks like this issue is out of date and Alexandria is using a stable algorithm. Closing.
