### ISSUE TITLE
Human size

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#37]
I found the need to print (file) sizes in a human readable manner, using the SI or IEC units.

Emacs has such a function, but it has some quirks, so I rewrote it:

```lisp
;; This is mostly inspired by Emacs 26.2.
(defun file-size-human-readable (file-size &optional flavor)
  "Produce a string showing FILE-SIZE in human-readable form.

Optional second argument FLAVOR controls the units and the display format:

 If FLAVOR is nil or omitted, each kilobyte is 1024 bytes and the produced
    suffixes are \"k\", \"M\", \"G\", \"T\", etc.
 If FLAVOR is `si', each kilobyte is 1000 bytes and the produced suffixes
    are \"k\", \"M\", \"G\", \"T\", etc.
 If FLAVOR is `iec', each kilobyte is 1024 bytes and the produced suffixes
    are \"KiB\", \"MiB\", \"GiB\", \"TiB\", etc."
  (let ((power (if (or (null flavor) (eq flavor 'iec))
                   1024.0
                   1000.0))
        (post-fixes
          ;; none, kilo, mega, giga, tera, peta, exa, zetta, yotta
          (list "" "k" "M" "G" "T" "P" "E" "Z" "Y"))
        (format-string "~d~a~a"))
    (loop while (and (>= file-size power) (rest post-fixes))
          do (setf file-size (/ file-size power)
                   post-fixes (rest post-fixes)))
    (if (> (abs (- file-size (round file-size))) 0.05)
        (setf format-string "~,1f~a~a")
        (setf file-size (round file-size)))
    (format nil format-string
            file-size
            (if (and (eq flavor 'iec) (string= (first post-fixes) "k"))
                "K"
                (first post-fixes))
            (cond
              ((and (eq flavor 'iec)
                    (string= (first post-fixes) ""))
               "B")
              ((eq flavor 'iec) "iB")
              (t "")))))
```

Would this be a good candidate for Serapeum?  If not, another library to suggest?

**Comment by ruricolist** [comment]
I like the idea, but isn't Emacs code GPL? Serapeum is MIT so I don't think anything directly ported from Emacs could be included?

**Comment by ruricolist** [comment]
Just to be clear: this is a function I would definitely like to have. If you can do a clean implementation, I will merge it.

**Comment by Ambrevar** [comment]
My implementation is a rewrite ;)

I could "rewrite more" if you think this could cause some licensing
issue.

**Comment by ruricolist** [comment]
I've added this, but I broke it into pieces that should be separately useful: `si-prefix` to derive the SI or IEC prefix for a number, `format-file-size-human-readable` to format a file size you already have, and `file-size-human-readable` itself.

**Comment by Ambrevar** [comment]
Thanks, looking great!

I was going to suggest a different, shorter name for the function (sorry
for being late): `format-human-size`.
Indeed, this function takes a number as argument, so it can be any size,
not necessarily that of a file.

Also see the comment I've sent in the commit about the spacing.

Thanks a lot for including this! :)

**Comment by Ambrevar** [comment]
Nit: In the description you mention "Inspired by the function of the same name in Emacs" but it's not anymore now that you've split the function.
