### ISSUE TITLE
executable find and binary path

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#39]
I like Emacs' `executable-find`.
Here is a quick hack that works in Common Lisp:

```lisp
(defun executable-find (command)
  "Search for COMMAND in the PATH and return the absolute file name.
Return nil if COMMAND is not found anywhere."
  (multiple-value-bind (path)
      (ignore-errors
       (uiop:run-program (format nil "command -v ~A" command)
                         :output '(:string :stripped t)))
    path))
```

Now obviously to implement it properly we would not use the `command` executable.

In particular, this  can be useful to locate the path of the Lisp binary we are running, e.g. with

```lisp
(executable-path (uiop:argv0))
```

**Comment by ruricolist** [comment]
I actually just wrote something like this for [another project](https://github.com/ruricolist/overlord/blob/b6ced888ef704bb4e016c56b18cb3103024a1f5e/cmd.lisp#L255), so I can just bring it over.

**Comment by Ambrevar** [comment]
That'd be great!

**Comment by ruricolist** [comment]
Done. 

We both managed to forget that `command` is a shell built-in, not an executable.

**Comment by Ambrevar** [comment]
Thanks!
