### ISSUE TITLE
Guix package compilation error

### ISSUE THREAD

**Issue by Ambrevar** [ruricolist/serapeum#42]
```lisp
; compiling (DEFUN FLOAT-PRECISION-CONTAGION ...)
; file: /gnu/store/81mwbkhih0v063r2cbs2b9kp70dk4l39-sbcl-serapeum-0.0.0-0.9cc0f9c/share/common-lisp/sbcl-source/serapeum/numbers.lisp
; in: DEFUN FLOAT-PRECISION-CONTAGION
;     (SERAPEUM:OP
;       (+ SERAPEUM::_ SERAPEUM::ZERO))
; 
; caught ERROR:
;   during macroexpansion of
;   (OP
;     (+ _ ZERO)).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    The function SERAPEUM/OP::EXTRACT-OP-ENV is undefined.

;     (MAPCAR
;      (SERAPEUM:OP
;        (+ SERAPEUM::_ SERAPEUM::ZERO))
;      SERAPEUM::NS)
; --> LET 
; ==>
;   (SB-KERNEL:%COERCE-CALLABLE-TO-FUN
;    (SERAPEUM:OP
;      (+ SERAPEUM::_ SERAPEUM::ZERO)))
; 
; note: The first argument never returns a value.

;     (SERAPEUM:OP
;       (* SERAPEUM::_ 0))
; 
; caught ERROR:
[...]
```

Any idea where that could come from?

**Comment by Ambrevar** [comment]
A clue: Guix uses `compile-bundle-op` and since `extract-op-env` is used by the `op` macro while unexported, it does not exist at compile time for the other files using `op`.

**Comment by Ambrevar** [comment]
Possible fixes:

- Either export `extract-op-env` (at compile time).
- Or turn it into a macro.

**Comment by ruricolist** [comment]
I've pushed a potential fix; would you mind trying again?

**Comment by Ambrevar** [comment]
It worked, thanks!
Can you explain why this works?  I thought that `serial t` was enough to ensure all preceding files were a dependency of the current file.

**Comment by ruricolist** [comment]
Different modules in a system can be serial or not serial. In Serapeum, the `:serial t` in the system definition only applies to the top level (the ordering of modules) -- the individual modules have `:serial nil`, just to avoid needless recompilation. But evidently there were some dependencies I missed.

**Comment by Ambrevar** [comment]
Oh, just notcied the `serial nil` now, makes total sense, thanks!
