### ISSUE TITLE
guideline for contributing

### ISSUE THREAD

**Issue by arademaker** [ruricolist/serapeum#48]
What is the guideline for contributing to this library? Maybe you can consider add here the macro `with-open-fileS`:

https://gist.github.com/arademaker/50aa74e490bf2160547cb212c9a1bf05#gistcomment-3171108

**Comment by ruricolist** [comment]
I like the general idea, although perhaps it should be `with-open-files*` with a star to show that the files are being bound sequentially?

**Comment by arademaker** [comment]
Hum, I like the name and I believe the plural has a clear message. But if the library has some names convention, I agree with the star in the end.

**Comment by ruricolist** [comment]
The advantage of having the star is that it leaves open the possibility of adding a version without a star that sets up the bindings in "parallel" (like let vs. let*). 

I can't think of a situation right now where that might be useful, but one might exist.

**Comment by ruricolist** [comment]
I think it would be good to have this in Serapeum; I can add it myself or you can make a pull request if you would prefer.

**Comment by arademaker** [comment]
But let is a special form, not a macro. According http://www.lispworks.com/documentation/HyperSpec/Body/s_let_l.htm

At macro time, I don’t see how parallel execution would be possible. I can make a PR if someone tell me what is the way to go. A new file and change the ASD?

**Comment by ruricolist** [comment]
I don't mean "parallel" in the sense of concurrent, but "parallel" in the sense that `let` or `psetf` is parallel: the bindings introduced by clause X are not visible in clause X+1, but only in the body (like `let*` or `psetf`).

I think files.lisp would be the right place for the macro. And you would have to export it in packages.lisp.
