### ISSUE TITLE
Really need `back` method for `queue`!

### ISSUE THREAD

**Issue by minghu6** [ruricolist/serapeum#67]
Some times, maybe more frequently, you really need get the tail element of the `queue`.
Though, I can write my own version as a workaround:

```lisp
(defun back (serapeum-queue)
  (alexandria:last-elt (qlist serapeum-queue)))
```
Supply a `back` method for queue from `serapeum` is the better way.
since there is already a `front` method:

https://github.com/ruricolist/serapeum/blob/408abccd519254efe877d49aeb4c2b912bd0ffc0/queue.lisp#L146

**Comment by ruricolist** [comment]
That's a good idea and it can be done in constant time (without traversing the list).

**Comment by minghu6** [comment]
En.., So, add enhancement label for this issue?
