### ISSUE TITLE
Serapeum cannot be asdf:load-source-op'd

### ISSUE THREAD

**Issue by astrangeguy** [ruricolist/serapeum#83]
I have a workflow and build system that builds a lisp image without creating fasl's on the way (don't ask) and serapeum is not loadable from source.

The culprit is `+lock-class+` in `threads.lisp` which is evaluated by the load-time-eval reader macro in the same file, while the symbol is still unbound.

I would propose to just inline the definition without the defconstant since the constant is not used elsewhere.

**Comment by ruricolist** [comment]
Sounds reasonable. If you want to make a PR I'll merge it.
