### ISSUE TITLE
defun* is not available in uiop anymore

### ISSUE THREAD

**Issue by Yehouda** [ruricolist/serapeum#94]
The file **definitions.lisp** refers to **uiop:defun***, but that does not exist in asdf 3.3.5 anymore. 
It gives an error during compilation. 

In lispworks, the error looks like that:
````

**++++ Error between functions:
  Symbol "DEFUN*" not found at all in the UIOP/DRIVER package.

**Comment by ruricolist** [comment]
This was removed in 04fccff3eeb4596d14c3cb089889ddb1e09541ab. You may need to update Quicklisp.
